# -*- ruby -*-
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  vms = [
    {
      :id => "debian-stretch-amd64",
      :box => "bento/debian-9.0",
    },
    {
      :id => "ubuntu-16.04-i386",
      :box => "bento/ubuntu-16.04-i386",
    },
    {
      :id => "ubuntu-16.04-amd64",
      :box => "bento/ubuntu-16.04",
    },
    {
      :id => "ubuntu-17.04-i386",
      :box => "bento/ubuntu-17.04-i386",
    },
    {
      :id => "ubuntu-17.04-amd64",
      :box => "bento/ubuntu-17.04",
    },
  ]

  vms.each do |vm|
    config.vm.define(vm[:id]) do |node|
      node.vm.box = vm[:box]
      node.vm.provision(:shell, :privileged => false, :path => "build-deb.sh")
    end
  end
end
